# -*- coding: utf-8 -*-
"""Project_M07_2_OCR Using YOLOv11 and CRNN

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1tBsV1pyhYuol_18zdt8RmAM3EItlBwve
"""

# !pip install -U gdown ultralytics scikit-learn albumentations timm torchinfo

!pip install -qq ultralytics easyocr Levenshtein

!gdown 15bTQg7W2NXg68ERJDSpY1t7EtL8eJ7az
!mkdir -p datasets
!unzip -q icdar2003.zip -d datasets

# Commented out IPython magic to ensure Python compatibility.
import os
import random
import shutil
import time
import xml.etree.ElementTree as ET

import cv2
import matplotlib.pyplot as plt
import numpy as np
import timm
import torch
import torch.nn as nn
import ultralytics
import yaml
from PIL import Image
from sklearn.model_selection import train_test_split
from torch.nn import functional as F
from torch.utils.data import DataLoader, Dataset
from torchvision import transforms
from ultralytics import YOLO

import json
import easyocr
from transformers import TrOCRProcessor, VisionEncoderDecoderModel
import Levenshtein

# Configure matplotlib for inline display in Jupyter notebooks
# %matplotlib inline

ultralytics.checks()
device = "cuda" if torch.cuda.is_available() else "cpu"
print(f"Using device: {device}")

"""---
# PART 1: TEXT DETECTION TRAINING (YOLO)
## 1. Extract Data from XML for Detection
"""

def extract_data_from_xml(path):
    tree = ET.parse(path)
    root = tree.getroot()

    image_paths = []
    image_sizes = []
    image_labels = []
    bounding_boxes = []

    for image in root:
        bbs_of_image = []
        labels_of_image = []

        for bbs in image.findall("taggedRectangles"):
            for bb in bbs:
                # check non-alphabet and non-number
                if not bb[0].text.isalnum():
                    continue

                if "é" in bb[0].text.lower() or "ñ" in bb[0].text.lower():
                    continue

                bbs_of_image.append(
                    [
                        float(bb.attrib["x"]),
                        float(bb.attrib["y"]),
                        float(bb.attrib["width"]),
                        float(bb.attrib["height"]),
                    ]
                )
                labels_of_image.append(bb[0].text.lower())

        image_paths.append(image[0].text)
        image_sizes.append((int(image[1].attrib["x"]), int(image[1].attrib["y"])))
        bounding_boxes.append(bbs_of_image)
        image_labels.append(labels_of_image)

    return image_paths, image_sizes, image_labels, bounding_boxes

dataset_dir = "datasets/SceneTrialTrain"
words_xml_path = os.path.join(dataset_dir, "words.xml")
image_paths, image_sizes, image_labels, bounding_boxes = extract_data_from_xml(
    words_xml_path
)

print(f"Number of images: {len(image_paths)}")
print(f"Example image path: {image_paths[0]}")
print(f"Example image size: {image_sizes[0]}")
print(f"Example bounding boxes: {bounding_boxes[0][:2]}")
print(f"Example labels: {image_labels[0][:2]}")

"""## 2. Convert to YOLO Format"""

def convert_to_yolo_format(image_paths, image_sizes, bounding_boxes):
    yolo_data = []

    for img_path, img_size, bbs in zip(image_paths, image_sizes, bounding_boxes):
        img_w, img_h = img_size
        yolo_bbs = []

        for bb in bbs:
            x, y, w, h = bb
            x_center = (x + w / 2) / img_w
            y_center = (y + h / 2) / img_h
            w_norm = w / img_w
            h_norm = h / img_h

            yolo_bbs.append([0, x_center, y_center, w_norm, h_norm])

        yolo_data.append((img_path, yolo_bbs))

    return yolo_data


yolo_data = convert_to_yolo_format(image_paths, image_sizes, bounding_boxes)
print(f"Number of YOLO data: {len(yolo_data)}")
print(f"Example YOLO data: {yolo_data[0]}")

"""## 3. Train/Val Split for Detection"""

train_yolo_data, val_yolo_data = train_test_split(
    yolo_data, test_size=0.2, random_state=42
)

print(f"Train YOLO data: {len(train_yolo_data)}")
print(f"Val YOLO data: {len(val_yolo_data)}")

"""## 4. Save YOLO Data"""

def save_yolo_data(data, split, save_dir, dataset_dir):
    split_dir = os.path.join(save_dir, split)
    images_dir = os.path.join(split_dir, "images")
    labels_dir = os.path.join(split_dir, "labels")

    os.makedirs(images_dir, exist_ok=True)
    os.makedirs(labels_dir, exist_ok=True)

    for img_path, yolo_bbs in data:
        img_name = img_path.replace("/", "_")
        img_src = os.path.join(dataset_dir, img_path)
        img_dest = os.path.join(images_dir, img_name)

        shutil.copy(img_src, img_dest)

        label_name = img_name.replace(".JPG", ".txt")
        label_path = os.path.join(labels_dir, label_name)

        with open(label_path, "w") as f:
            for bb in yolo_bbs:
                f.write(f"{bb[0]} {bb[1]} {bb[2]} {bb[3]} {bb[4]}\n")

save_yolo_data_dir = "yolo_data"
save_yolo_data(train_yolo_data, "train", save_yolo_data_dir, dataset_dir)
save_yolo_data(val_yolo_data, "val", save_yolo_data_dir, dataset_dir)

"""## 5. Create YOLO Config YAML"""

class_labels = ["text"]
data_yaml = {
    "path": os.path.abspath(save_yolo_data_dir),
    "train": "train/images",
    "val": "val/images",
    "nc": 1,
    "names": class_labels,
}

yolo_yaml_path = os.path.join(save_yolo_data_dir, "data.yml")
with open(yolo_yaml_path, "w") as f:
    yaml.dump(data_yaml, f, default_flow_style=False)

print(f"YOLO config saved to: {yolo_yaml_path}")

"""## 6. Train YOLO Model"""

# Visualize YOLO training data
print("YOLO Training Data Visualization")
print("=" * 80)
print(f"Total train images: {len(train_yolo_data)}")
print(f"Total val images: {len(val_yolo_data)}")

# Display sample train images with bounding boxes
sample_train = random.sample(train_yolo_data, min(4, len(train_yolo_data)))

fig, axes = plt.subplots(1, 4, figsize=(20, 5))

for idx, (img_path, yolo_bbs) in enumerate(sample_train):
    full_path = os.path.join(dataset_dir, img_path)
    img = cv2.imread(full_path)
    if img is None:
        continue

    img = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)
    h, w = img.shape[:2]

    # Draw bounding boxes
    for bb in yolo_bbs:
        cls, x_center, y_center, bbox_w, bbox_h = bb
        x1 = int((x_center - bbox_w / 2) * w)
        y1 = int((y_center - bbox_h / 2) * h)
        x2 = int((x_center + bbox_w / 2) * w)
        y2 = int((y_center + bbox_h / 2) * h)

        cv2.rectangle(img, (x1, y1), (x2, y2), (0, 255, 0), 2)

    axes[idx].imshow(img)
    axes[idx].set_title(f"Train Image {idx+1}\nBBoxes: {len(yolo_bbs)}", fontsize=11, fontweight='bold')
    axes[idx].axis('off')

plt.suptitle('YOLO Training Data - Text Detection Samples', fontsize=14, fontweight='bold', y=1.00)
plt.tight_layout()
plt.show()

# Load YOLO model
yolo_model = YOLO("yolo11m.pt")

# Train model
yolo_results = yolo_model.train(
    data=yolo_yaml_path,
    epochs=80,
    imgsz=640,
    cache=True,
    patience=20,
    plots=True,
)

"""## 7. Evaluate YOLO Model"""

yolo_model_path = "runs/detect/train/weights/best.pt"
yolo_model = YOLO(yolo_model_path)
yolo_metrics = yolo_model.val()

"""---
# PART 2: TEXT RECOGNITION TRAINING (CRNN)
## 8. Extract and Crop Text Regions for Recognition
"""

def extract_data_from_xml_for_recognition(root_dir):
    xml_path = os.path.join(root_dir, "words.xml")
    tree = ET.parse(xml_path)
    root = tree.getroot()

    img_paths = []
    img_sizes = []
    img_labels = []
    bboxes = []

    for img in root:
        bbs_of_img = []
        labels_of_img = []

        for bbs in img.findall("taggedRectangles"):
            for bb in bbs:
                # check non-alphabet and non-number
                if not bb[0].text.isalnum():
                    continue

                if "é" in bb[0].text.lower() or "ñ" in bb[0].text.lower():
                    continue

                bbs_of_img.append(
                    [
                        float(bb.attrib["x"]),
                        float(bb.attrib["y"]),
                        float(bb.attrib["width"]),
                        float(bb.attrib["height"]),
                    ]
                )
                labels_of_img.append(bb[0].text.lower())

        img_path = os.path.join(root_dir, img[0].text)
        img_paths.append(img_path)
        img_sizes.append((int(img[1].attrib["x"]), int(img[1].attrib["y"])))
        bboxes.append(bbs_of_img)
        img_labels.append(labels_of_img)

    return img_paths, img_sizes, img_labels, bboxes

img_paths, img_sizes, img_labels, bboxes = extract_data_from_xml_for_recognition(
    dataset_dir
)
print(f"Total images: {len(img_paths)}")
print(f"Total bounding boxes: {sum([len(bbs) for bbs in bboxes])}")

"""## 9. Crop and Save Text Regions"""

def crop_text(img_paths, img_labels, bboxes, save_dir="cropped_text"):
    os.makedirs(save_dir, exist_ok=True)

    cropped_paths = []
    labels = []

    for img_path, img_label, bbox in zip(img_paths, img_labels, bboxes):
        img = cv2.imread(img_path)

        # Skip if image could not be loaded
        if img is None:
            print(f"Warning: Could not load image {img_path}")
            continue

        for i, (bb, label) in enumerate(zip(bbox, img_label)):
            x, y, w, h = bb
            x, y, w, h = int(x), int(y), int(w), int(h)

            # Ensure bounding box is within image bounds
            x = max(0, x)
            y = max(0, y)
            w = max(1, w)
            h = max(1, h)
            x_end = min(img.shape[1], x + w)
            y_end = min(img.shape[0], y + h)

            # Skip if bounding box is invalid
            if x_end <= x or y_end <= y:
                print(f"Warning: Invalid bounding box for {img_path}")
                continue

            cropped_img = img[y:y_end, x:x_end]

            # Skip if crop is empty
            if cropped_img.size == 0:
                print(f"Warning: Empty crop for {img_path} at bbox {bb}")
                continue

            img_name = os.path.basename(img_path).replace(".JPG", "")
            save_path = os.path.join(save_dir, f"{img_name}_{i}.jpg")

            cv2.imwrite(save_path, cropped_img)

            cropped_paths.append(save_path)
            labels.append(label)

    return cropped_paths, labels

cropped_img_paths, labels = crop_text(img_paths, img_labels, bboxes)
print(f"Total cropped images: {len(cropped_img_paths)}")
print(f"Example label: {labels[:5]}")

"""## 10. Prepare Characters and Encoding"""

# Define vocabulary
chars = "0123456789abcdefghijklmnopqrstuvwxyz-"
vocab_size = len(chars)
blank_char = "-"

char_to_idx = {char: idx + 1 for idx, char in enumerate(sorted(chars))}
idx_to_char = {idx: char for char, idx in char_to_idx.items()}

print(f"Vocabulary size: {vocab_size}")
print(f"char_to_idx: {char_to_idx}")

# Calculate max label length
max_label_len = max([len(label) for label in labels])
print(f"Max label length: {max_label_len}")

def encode(text, char_to_idx, max_label_len):
    encoded = []
    for char in text:
        encoded.append(char_to_idx[char])

    label_len = len(encoded)

    # Pad with 0s
    encoded += [0] * (max_label_len - len(encoded))

    return torch.LongTensor(encoded), torch.tensor(label_len, dtype=torch.long)


def decode(encoded_sequences, idx_to_char, blank_char="-"):
    decoded_sequences = []

    for seq in encoded_sequences:
        decoded_label = []
        prev_char = None

        for token in seq:
            if token != 0:
                char = idx_to_char[token.item()]
                if char != blank_char:
                    if char != prev_char or prev_char == blank_char:
                        decoded_label.append(char)
                prev_char = char

        decoded_sequences.append("".join(decoded_label))

    return decoded_sequences

"""## 12. Train/Val/Test Split for Recognition"""

seed = 0
val_size = 0.1
test_size = 0.1
is_shuffle = True

X_train, X_val, y_train, y_val = train_test_split(
    cropped_img_paths,
    labels,
    test_size=val_size,
    random_state=seed,
    shuffle=is_shuffle,
)

X_train, X_test, y_train, y_test = train_test_split(
    X_train,
    y_train,
    test_size=test_size,
    random_state=seed,
    shuffle=is_shuffle,
)

print(f"Train: {len(X_train)}, Val: {len(X_val)}, Test: {len(X_test)}")

"""## 13. Create PyTorch Dataset"""

class STRDataset(Dataset):
    def __init__(
        self,
        X,
        y,
        char_to_idx,
        max_label_len,
        label_encoder=None,
        transform=None,
    ):
        self.transform = transform
        self.img_paths = X
        self.labels = y
        self.char_to_idx = char_to_idx
        self.max_label_len = max_label_len
        self.label_encoder = label_encoder

    def __len__(self):
        return len(self.img_paths)

    def __getitem__(self, idx):
        label = self.labels[idx]
        img_path = self.img_paths[idx]
        img = Image.open(img_path).convert("RGB")

        if self.transform:
            img = self.transform(img)

        if self.label_encoder:
            encoded_label, label_len = self.label_encoder(
                label, self.char_to_idx, self.max_label_len
            )
        return img, encoded_label, label_len

"""## 15. Enhanced Data Transforms and DataLoaders"""

## Data Transforms
data_transforms = {
    "train": transforms.Compose(
        [
            transforms.Resize((100, 420), interpolation=2),
            transforms.ColorJitter(brightness=0.5, contrast=0.5, saturation=0.5),
            transforms.Grayscale(num_output_channels=1),
            transforms.GaussianBlur(kernel_size=3),
            transforms.RandomAffine(degrees=1, shear=1),
            transforms.RandomPerspective(distortion_scale=0.3, p=0.5, interpolation=3),
            transforms.RandomRotation(degrees=2),
            transforms.ToTensor(),
            transforms.Normalize((0.5,), (0.5,)),
        ]
    ),
    "val": transforms.Compose(
        [
            transforms.Resize((100, 420), interpolation=2),
            transforms.Grayscale(num_output_channels=1),
            transforms.ToTensor(),
            transforms.Normalize((0.5,), (0.5,)),
        ]
    ),
}

train_dataset = STRDataset(
    X_train,
    y_train,
    char_to_idx=char_to_idx,
    max_label_len=max_label_len,
    label_encoder=encode,
    transform=data_transforms["train"],
)

val_dataset = STRDataset(
    X_val,
    y_val,
    char_to_idx=char_to_idx,
    max_label_len=max_label_len,
    label_encoder=encode,
    transform=data_transforms["val"],
)

test_dataset = STRDataset(
    X_test,
    y_test,
    char_to_idx=char_to_idx,
    max_label_len=max_label_len,
    label_encoder=encode,
    transform=data_transforms["val"],
)

train_batch_size = 256
test_batch_size = 256

train_loader = DataLoader(train_dataset, batch_size=train_batch_size, shuffle=True)
val_loader = DataLoader(val_dataset, batch_size=test_batch_size, shuffle=False)
test_loader = DataLoader(test_dataset, batch_size=test_batch_size, shuffle=False)

"""## 16. Define CRNN Model"""

class CRNN(nn.Module):
    def __init__(
        self, vocab_size, hidden_size, n_layers, dropout=0.2, unfreeze_layers=3
    ):
        super(CRNN, self).__init__()

        backbone = ***Your Code Here***
        modules = list(backbone.children())[:-2]
        modules.append(nn.AdaptiveAvgPool2d((1, None)))
        self.backbone = nn.Sequential(*modules)

        # Unfreeze the last few layers
        for parameter in self.backbone[-unfreeze_layers:].parameters():
            parameter.requires_grad = True

        # ResNet34 outputs 512 channels
        self.mapSeq = nn.Sequential(
            nn.Linear(512, 512), nn.ReLU(), nn.Dropout(dropout)
        )

        self.gru = nn.GRU(
            512,
            hidden_size,
            n_layers,
            bidirectional=True,
            batch_first=True,
            dropout=dropout if n_layers > 1 else 0,
        )
        self.layer_norm = nn.LayerNorm(hidden_size * 2)

        self.out = nn.Sequential(
            ***Your Code Here***
        )

    def forward(self, x):
        x = ***Your Code Here***
        x = x.permute(0, 3, 1, 2)
        x = x.view(x.size(0), x.size(1), -1)  # Flatten the feature map
        x = ***Your Code Here***
        x, _ = ***Your Code Here***
        x = self.layer_norm(x)
        x = ***Your Code Here***
        x = x.permute(1, 0, 2)  # Based on CTC

        return x

hidden_size = 256
n_layers = 3
dropout_prob = 0.2
unfreeze_layers = 3
device = "cuda" if torch.cuda.is_available() else "cpu"

crnn_model = CRNN(
    vocab_size=vocab_size,
    hidden_size=hidden_size,
    n_layers=n_layers,
    dropout=dropout_prob,
    unfreeze_layers=unfreeze_layers,
).to(device)

"""## 17. Training Functions"""

def evaluate(model, dataloader, criterion, device):
    model.eval()
    losses = []
    with torch.no_grad():
        for idx, (inputs, labels, labels_len) in enumerate(dataloader):
            inputs = inputs.to(device)
            labels = labels.to(device)
            labels_len = labels_len.to(device)

            outputs = model(inputs)
            logits_lens = torch.full(
                size=(outputs.size(1),), fill_value=outputs.size(0), dtype=torch.long
            ).to(device)

            loss = criterion(outputs, labels, logits_lens, labels_len)
            losses.append(loss.item())

    loss = sum(losses) / len(losses)

    return loss


def fit(
    model,
    train_loader,
    val_loader,
    criterion,
    optimizer,
    scheduler,
    device,
    epochs,
    max_grad_norm=2,
):
    train_losses = []
    val_losses = []

    for epoch in range(epochs):
        start = time.time()

        batch_train_losses = []

        model.train()
        for idx, (inputs, labels, labels_len) in enumerate(train_loader):
            inputs = inputs.to(device)
            labels = labels.to(device)
            labels_len = labels_len.to(device)

            optimizer.zero_grad()

            outputs = model(inputs)

            logits_lens = torch.full(
                size=(outputs.size(1),),
                fill_value=outputs.size(0),
                dtype=torch.long,
            ).to(device)

            loss = criterion(outputs, labels.cpu(), logits_lens.cpu(), labels_len.cpu())

            loss.backward()

            torch.nn.utils.clip_grad_norm_(model.parameters(), max_grad_norm)

            optimizer.step()

            batch_train_losses.append(loss.item())

        train_loss = sum(batch_train_losses) / len(batch_train_losses)
        train_losses.append(train_loss)

        val_loss = evaluate(model, val_loader, criterion, device)
        val_losses.append(val_loss)

        print(
            f"EPOCH {epoch + 1}:\tTrain loss: {train_loss:.4f}\tVal loss: {val_loss:.4f}\t\t Time: {time.time() - start:.2f} seconds"
        )

        scheduler.step()

    return train_losses, val_losses

def decode_label(encoded_sequences, idx_to_char, blank_char="-"):
    decoded_sequences = []

    for seq in encoded_sequences:
        decoded_label = []
        for idx, token in enumerate(seq):
            if token != 0:
                char = idx_to_char[token.item()]
                if char != blank_char:
                    decoded_label.append(char)

        decoded_sequences.append("".join(decoded_label))

    return decoded_sequences

# Visualize training data batch
train_features, train_labels, train_lengths = next(iter(train_loader))

print("Training Data Batch Visualization")
print("=" * 80)
print(f"Batch size: {train_features.shape[0]}")
print(f"Image shape: {train_features.shape}")
print(f"Labels shape: {train_labels.shape}")
print(f"Label lengths: {train_lengths[:8]}")

# Decode labels to show actual text
decoded_labels = decode_label(train_labels, idx_to_char)
print(f"\nSample labels: {decoded_labels[:8]}")

# Display first 8 images with their labels
fig, axes = plt.subplots(2, 4, figsize=(16, 6))
axes = axes.flatten()

for i in range(min(8, len(train_features))):
    img = train_features[i].cpu().numpy()
    img = np.transpose(img, (1, 2, 0))  # Convert from CHW to HWC

    axes[i].imshow(img, cmap='gray')
    axes[i].set_title(f"Label: {decoded_labels[i]}", fontsize=10, fontweight='bold')
    axes[i].axis('off')

plt.tight_layout()
plt.suptitle('Training Data Batch - CRNN Input Samples', fontsize=14, fontweight='bold', y=1.02)
plt.show()

"""## 18. Train CRNN Model"""

epochs = 80
lr = 1e-3
weight_decay = 1e-5
scheduler_step_size = epochs * 0.5

criterion = nn.CTCLoss(
    blank=char_to_idx[blank_char],
    zero_infinity=True,
    reduction="mean",
)
optimizer = torch.optim.Adam(
    crnn_model.parameters(),
    lr=lr,
    weight_decay=weight_decay,
)
scheduler = torch.optim.lr_scheduler.StepLR(
    optimizer, step_size=scheduler_step_size, gamma=0.1
)

train_losses, val_losses = fit(
    crnn_model,
    train_loader,
    val_loader,
    criterion,
    optimizer,
    scheduler,
    device,
    epochs,
)

"""## 19. Plot Training History"""

fig, ax = plt.subplots(1, 2, figsize=(12, 5))
ax[0].plot(train_losses)
ax[0].set_title("Training Loss")
ax[0].set_xlabel("Epoch")
ax[0].set_ylabel("Loss")
ax[1].plot(val_losses, color="orange")
ax[1].set_title("Val Loss")
ax[1].set_xlabel("Epoch")
ax[1].set_ylabel("Loss")
plt.show()

"""## 20. Visualize Predictions"""

# View samples from test set
sample_result = []

for i in range(20):
    idx = np.random.randint(len(test_dataset))
    img, label, label_len = test_dataset[idx]
    img = img.to(device)
    label = label.to(device)
    label = decode_label([label], idx_to_char)[0]
    logits = crnn_model(img.unsqueeze(0))

    pred_text = decode(logits.permute(1, 0, 2).argmax(2), idx_to_char)[0]

    sample_result.append((img, label, pred_text))

fig = plt.figure(figsize=(20, 5))
for i in range(20):
    ax = fig.add_subplot(4, 5, i + 1, xticks=[], yticks=[])

    img, label, pred_text = sample_result[i]
    img = img.cpu()
    title = f"Truth: {label} | Pred: {pred_text}"

    ax.imshow(img.permute(1, 2, 0), cmap="gray")
    ax.set_title(title)

plt.show()

# Save CRNN model
crnn_model_path = "ocr_crnn.pt"
torch.save(crnn_model.state_dict(), crnn_model_path)
print(f"CRNN model saved to: {crnn_model_path}")

# YOLO model is already saved in runs/detect/train/weights/best.pt
print(f"YOLO model saved to: runs/detect/train/weights/best.pt")

"""## 21. Save Models

---
# PART 3: MODEL COMPARISON

So sánh 3 models trên test dataset:
- **YOLO + CRNN (Ours)**
- **YOLO + TrOCR**
- **EasyOCR (End-to-End)**

Đánh giá theo:
- Character Accuracy
- Word Accuracy  
- Inference Speed

Với 2 confidence thresholds: **0.3**

## 22. Load Models for Comparison
"""

# Load YOLO + CRNN (our trained models)
yolo_model_path = "runs/detect/train/weights/best.pt"
crnn_model_path = "ocr_crnn.pt"

yolo_det = YOLO(yolo_model_path)
print("YOLO model loaded")

# Load CRNN model
crnn_inference = CRNN(
    vocab_size=vocab_size,
    hidden_size=hidden_size,
    n_layers=n_layers,
    dropout=dropout_prob,
    unfreeze_layers=unfreeze_layers,
).to(device)
crnn_inference.load_state_dict(torch.load(crnn_model_path, map_location=device))
crnn_inference.eval()
print("CRNN model loaded")

# Load TrOCR
print("Loading TrOCR model...")
trocr_processor = TrOCRProcessor.from_pretrained("microsoft/trocr-base-printed")
trocr_model = VisionEncoderDecoderModel.from_pretrained("microsoft/trocr-base-printed").to(device)
trocr_model.eval()
print("TrOCR model loaded\n")

# ============================================================================
# HIỂN THỊ CẤU TRÚC CHI TIẾT CỦA TrOCR MODEL
# ============================================================================
print("="*100)
print("TROCR MODEL ARCHITECTURE - ENCODER & DECODER COMPONENTS")
print("="*100)

# 1. Model Config Info
print("\n[1] MODEL CONFIGURATION:")
print("-" * 100)
print(f"  • Model Type: {type(trocr_model).__name__}")
print(f"  • Device: {device}")
print(f"  • Total Parameters: {sum(p.numel() for p in trocr_model.parameters()):,}")
print(f"  • Trainable Parameters: {sum(p.numel() for p in trocr_model.parameters() if p.requires_grad):,}")

# 2. Encoder Structure
print("\n[2] ENCODER (Vision Component - DeiT/ViT):")
print("-" * 100)
encoder = trocr_model.encoder
print(f"  • Type: {type(encoder).__name__}")
print(f"  • Config: {encoder.config}")
print("\n  • Encoder Layers:")
for name, module in encoder.named_children():
    if not name.startswith('_'):
        param_count = sum(p.numel() for p in module.parameters())
        print(f"      - {name}: {type(module).__name__} ({param_count:,} params)")

# 3. Decoder Structure
print("\n[3] DECODER (Text Generation Component - GPT-2 based):")
print("-" * 100)
decoder = trocr_model.decoder
print(f"  • Type: {type(decoder).__name__}")
print(f"  • Config: {decoder.config}")
print("\n  • Decoder Layers:")
for name, module in decoder.named_children():
    if not name.startswith('_'):
        param_count = sum(p.numel() for p in module.parameters())
        print(f"      - {name}: {type(module).__name__} ({param_count:,} params)")

# 4. Model Config Details
print("\n[4] DETAILED MODEL CONFIGURATION:")
print("-" * 100)
config = trocr_model.config
decoder_config = config.decoder
print(f"  • is_encoder_decoder: {config.is_encoder_decoder}")
print(f"  • Vocab Size: {decoder_config.vocab_size}")
print(f"  • Max Position Embeddings: {getattr(decoder_config, 'max_position_embeddings', 'N/A')}")
print(f"  • Hidden Size: {decoder_config.hidden_size}")
print(f"  • Num Hidden Layers: {decoder_config.num_hidden_layers}")
print(f"  • Num Attention Heads: {decoder_config.num_attention_heads}")
print(f"  • Intermediate Size: {getattr(decoder_config, 'intermediate_size', 'N/A')}")
print(f"  • Dropout: {getattr(decoder_config, 'dropout', getattr(decoder_config, 'hidden_dropout_prob', 'N/A'))}")
print(f"  • Attention Dropout: {getattr(decoder_config, 'attention_dropout', getattr(decoder_config, 'attention_probs_dropout_prob', 'N/A'))}")

# 5. Full Model Summary
print("\n[5] FULL MODEL STRUCTURE:")
print("-" * 100)
print(trocr_model)

print("\n" + "="*100)
print("TrOCR Model loaded and ready for inference!")
print("="*100 + "\n")

# Load EasyOCR
print("Loading EasyOCR model...")
easyocr_reader = easyocr.Reader(['en'], gpu=torch.cuda.is_available())
print("EasyOCR model loaded")

"""## 23. Define Evaluation Metrics"""

def calculate_char_accuracy(pred, gt):
    """Calculate character-level accuracy using Levenshtein distance"""
    if len(gt) == 0:
        return 1.0 if len(pred) == 0 else 0.0

    distance = Levenshtein.distance(pred.lower(), gt.lower())
    accuracy = 1 - (distance / max(len(pred), len(gt)))
    return max(0, accuracy)

def calculate_word_accuracy(pred, gt):
    """Calculate exact word match accuracy"""
    return 1.0 if pred.lower().strip() == gt.lower().strip() else 0.0

def calculate_metrics(predictions, ground_truths):
    """Calculate average metrics for a list of predictions"""
    char_accs = []
    word_accs = []

    for pred, gt in zip(predictions, ground_truths):
        char_accs.append(calculate_char_accuracy(pred, gt))
        word_accs.append(calculate_word_accuracy(pred, gt))

    return {
        'char_accuracy': np.mean(char_accs) * 100,
        'word_accuracy': np.mean(word_accs) * 100,
        'total_samples': len(predictions)
    }

"""## 24. Prepare Test Dataset from Full Images"""

# Create test set from validation split (for evaluation)
# We'll use a subset of val_yolo_data for testing
test_samples = val_yolo_data[:50]  # Use first 50 images from validation

# Extract ground truth for each text region in test images
test_data = []
for img_rel_path, yolo_bbs in test_samples:
    img_path = os.path.join(dataset_dir, img_rel_path)

    # Find corresponding labels
    for idx, (img_p, labels_list, bbs_list) in enumerate(zip(image_paths, image_labels, bounding_boxes)):
        if img_p == img_rel_path:
            # Load image
            img = cv2.imread(img_path)
            if img is None:
                continue

            # For each bounding box, store image, bbox, and label
            for bb, label in zip(bbs_list, labels_list):
                x, y, w, h = [int(v) for v in bb]
                test_data.append({
                    'image_path': img_path,
                    'bbox': (x, y, w, h),
                    'label': label,
                    'image': img
                })
            break

print(f"Test dataset prepared: {len(test_data)} text regions from {len(test_samples)} images")

"""## 25. YOLO + CRNN, YOLO + TrOCR and EasyOCR"""

# Transform for CRNN inference
crnn_transform = transforms.Compose([
    transforms.Resize((100, 420)),
    transforms.Grayscale(num_output_channels=1),
    transforms.ToTensor(),
    transforms.Normalize((0.5,), (0.5,)),
])

def inference_yolo_crnn(img_path, conf_threshold=0.3):
    """Inference using YOLO + CRNN pipeline"""
    predictions = []

    # YOLO Detection
    results = yolo_det(img_path, verbose=False, conf=conf_threshold)
    detections = json.loads(results[0].to_json())

    img = cv2.imread(img_path)

    for det in detections:
        if det['confidence'] < conf_threshold:
            continue

        # Get bounding box
        box = det['box']
        x1, y1, x2, y2 = int(box['x1']), int(box['y1']), int(box['x2']), int(box['y2'])

        # Crop text region
        cropped = img[y1:y2, x1:x2]
        if cropped.size == 0:
            continue

        # Convert to PIL Image
        cropped_pil = Image.fromarray(cv2.cvtColor(cropped, cv2.COLOR_BGR2RGB))

        # CRNN Recognition
        img_tensor = crnn_transform(cropped_pil).unsqueeze(0).to(device)
        with torch.no_grad():
            logits = crnn_inference(img_tensor)
            pred_text = decode(logits.permute(1, 0, 2).argmax(2), idx_to_char)[0]

        predictions.append({
            'bbox': (x1, y1, x2-x1, y2-y1),
            'text': pred_text,
            'confidence': det['confidence']
        })

    return predictions

def inference_yolo_trocr(img_path, conf_threshold=0.3):
    """Inference using YOLO + TrOCR pipeline"""
    predictions = []

    # YOLO Detection
    results = yolo_det(img_path, verbose=False, conf=conf_threshold)
    detections = json.loads(results[0].to_json())

    img = cv2.imread(img_path)

    for det in detections:
        if det['confidence'] < conf_threshold:
            continue

        # Get bounding box
        box = det['box']
        x1, y1, x2, y2 = int(box['x1']), int(box['y1']), int(box['x2']), int(box['y2'])

        # Crop text region
        cropped = img[y1:y2, x1:x2]
        if cropped.size == 0:
            continue

        # Convert to PIL Image (RGB)
        cropped_pil = Image.fromarray(cv2.cvtColor(cropped, cv2.COLOR_BGR2RGB))

        # TrOCR Recognition
        pixel_values = trocr_processor(cropped_pil, return_tensors="pt").pixel_values.to(device)
        with torch.no_grad():
            generated_ids = trocr_model.generate(pixel_values)
            pred_text = trocr_processor.batch_decode(generated_ids, skip_special_tokens=True)[0]

        predictions.append({
            'bbox': (x1, y1, x2-x1, y2-y1),
            'text': pred_text,
            'confidence': det['confidence']
        })

    return predictions

def inference_easyocr(img_path, conf_threshold=0.3):
    """Inference using EasyOCR (end-to-end)"""
    predictions = []

    # EasyOCR Detection + Recognition
    results = easyocr_reader.readtext(img_path)

    for result in results:
        bbox, text, confidence = result

        if confidence < conf_threshold:
            continue

        # Convert bbox format
        x_coords = [p[0] for p in bbox]
        y_coords = [p[1] for p in bbox]
        x1, y1 = int(min(x_coords)), int(min(y_coords))
        x2, y2 = int(max(x_coords)), int(max(y_coords))

        predictions.append({
            'bbox': (x1, y1, x2-x1, y2-y1),
            'text': text,
            'confidence': confidence
        })

    return predictions

def match_predictions_to_ground_truth(predictions, ground_truths, iou_threshold=0.3):
    """Match predicted boxes to ground truth boxes using IoU"""
    matched_preds = []
    matched_gts = []

    for gt in ground_truths:
        gt_bbox = gt['bbox']
        best_iou = 0
        best_pred = None

        for pred in predictions:
            pred_bbox = pred['bbox']

            # Calculate IoU
            x1_gt, y1_gt, w_gt, h_gt = gt_bbox
            x1_pred, y1_pred, w_pred, h_pred = pred_bbox

            x1_inter = max(x1_gt, x1_pred)
            y1_inter = max(y1_gt, y1_pred)
            x2_inter = min(x1_gt + w_gt, x1_pred + w_pred)
            y2_inter = min(y1_gt + h_gt, y1_pred + h_pred)

            if x2_inter > x1_inter and y2_inter > y1_inter:
                inter_area = (x2_inter - x1_inter) * (y2_inter - y1_inter)
                area_gt = w_gt * h_gt
                area_pred = w_pred * h_pred
                union_area = area_gt + area_pred - inter_area
                iou = inter_area / union_area if union_area > 0 else 0

                if iou > best_iou:
                    best_iou = iou
                    best_pred = pred

        if best_iou >= iou_threshold and best_pred:
            matched_preds.append(best_pred['text'])
            matched_gts.append(gt['label'])

    return matched_preds, matched_gts

def evaluate_model(inference_func, test_samples, model_name, conf_threshold=0.3):
    """Evaluate a model on test samples"""
    print(f"\n{'='*60}")
    print(f"Evaluating {model_name}...")
    print(f"{'='*60}")

    all_predictions = []
    all_ground_truths = []
    total_time = 0
    processed_images = 0

    # Group test data by image
    images_dict = {}
    for item in test_samples:
        img_path = item['image_path']
        if img_path not in images_dict:
            images_dict[img_path] = []
        images_dict[img_path].append(item)

    for img_path, gt_items in images_dict.items():
        try:
            # Run inference
            start_time = time.time()
            predictions = inference_func(img_path, conf_threshold=conf_threshold)
            elapsed_time = time.time() - start_time
            total_time += elapsed_time
            processed_images += 1

            # Match predictions to ground truth
            matched_preds, matched_gts = match_predictions_to_ground_truth(
                predictions, gt_items, iou_threshold=0.3
            )

            all_predictions.extend(matched_preds)
            all_ground_truths.extend(matched_gts)

        except Exception as e:
            print(f"Error processing {img_path}: {e}")
            continue

    # Calculate metrics
    if len(all_predictions) > 0:
        metrics = calculate_metrics(all_predictions, all_ground_truths)
        avg_time = total_time / processed_images if processed_images > 0 else 0

        print(f"\nResults for {model_name}:")
        print(f"  - Character Accuracy: {metrics['char_accuracy']:.2f}%")
        print(f"  - Word Accuracy: {metrics['word_accuracy']:.2f}%")
        print(f"  - Average Time per Image: {avg_time:.4f}s")
        print(f"  - Total Images Processed: {processed_images}")
        print(f"  - Total Text Regions Matched: {len(all_predictions)}")

        return {
            'model': model_name,
            'char_acc': metrics['char_accuracy'],
            'word_acc': metrics['word_accuracy'],
            'avg_time': avg_time,
            'total_images': processed_images,
            'matched_regions': len(all_predictions)
        }
    else:
        print(f"No predictions matched for {model_name}!")
        return None

"""## 26. Run Evaluation Functions"""

# Test with confidence threshold 0.3
conf_threshold = 0.3
print(f"\n\n{'#'*80}")
print(f"# EVALUATION WITH CONFIDENCE THRESHOLD = {conf_threshold}")
print(f"{'#'*80}\n")

# Evaluate YOLO + CRNN
results_yolo_crnn = evaluate_model(
    inference_yolo_crnn,
    test_data,
    "YOLO + CRNN (Ours)",
    conf_threshold=conf_threshold
)

# Evaluate YOLO + TrOCR
results_yolo_trocr = evaluate_model(
    inference_yolo_trocr,
    test_data,
    "YOLO + TrOCR",
    conf_threshold=conf_threshold
)

# Evaluate EasyOCR (end-to-end)
results_easyocr = evaluate_model(
    inference_easyocr,
    test_data,
    "EasyOCR (End-to-End)",
    conf_threshold=conf_threshold
)

# Store results for comparison
results_03 = [results_yolo_crnn, results_yolo_trocr, results_easyocr]

import pandas as pd

# Display comparison results for confidence threshold 0.3
print("\n" + "="*100)
print("COMPARISON RESULTS - CONFIDENCE THRESHOLD = 0.3")
print("="*100)

results = [r for r in results_03 if r]
if len(results) > 0:
    df_03 = pd.DataFrame(results)
    df_03 = df_03[['model', 'char_acc', 'word_acc', 'avg_time', 'matched_regions']]
    df_03.columns = ['Model', 'Char Acc (%)', 'Word Acc (%)', 'Speed (s/img)', 'Matched Regions']
    print(df_03.to_string(index=False))
    best_char_03 = df_03.loc[df_03['Char Acc (%)'].idxmax(), 'Model']
    best_word_03 = df_03.loc[df_03['Word Acc (%)'].idxmax(), 'Model']

    print("\n" + "="*100)
    print("SUMMARY")
    print("="*100)
    print(f"Confidence 0.3 - Best Char Acc: {best_char_03} | Best Word Acc: {best_word_03}")

if len(results_03) > 0:
    # Visualize results for confidence threshold 0.3
    fig, axes = plt.subplots(1, 3, figsize=(18, 6))

    colors = ['#2ecc71', '#3498db', '#e74c3c']
    df = df_03

    # Character Accuracy
    axes[0].bar(df['Model'], df['Char Acc (%)'], color=colors)
    axes[0].set_ylabel('Accuracy (%)', fontsize=12)
    axes[0].set_title('Character Accuracy (Conf=0.3)', fontsize=14, fontweight='bold')
    axes[0].set_ylim([0, 100])
    axes[0].grid(axis='y', alpha=0.3)
    axes[0].tick_params(axis='x', rotation=45)
    for i, v in enumerate(df['Char Acc (%)']):
        axes[0].text(i, v + 2, f'{v:.1f}%', ha='center', fontweight='bold', fontsize=10)

    # Word Accuracy
    axes[1].bar(df['Model'], df['Word Acc (%)'], color=colors)
    axes[1].set_ylabel('Accuracy (%)', fontsize=12)
    axes[1].set_title('Word Accuracy (Conf=0.3)', fontsize=14, fontweight='bold')
    axes[1].set_ylim([0, 100])
    axes[1].grid(axis='y', alpha=0.3)
    axes[1].tick_params(axis='x', rotation=45)
    for i, v in enumerate(df['Word Acc (%)']):
        axes[1].text(i, v + 2, f'{v:.1f}%', ha='center', fontweight='bold', fontsize=10)

    # Speed
    axes[2].bar(df['Model'], df['Speed (s/img)'], color=colors)
    axes[2].set_ylabel('Time (seconds)', fontsize=12)
    axes[2].set_title('Speed (Conf=0.3)', fontsize=14, fontweight='bold')
    axes[2].grid(axis='y', alpha=0.3)
    axes[2].tick_params(axis='x', rotation=45)

    max_speed = float(df['Speed (s/img)'].max())
    axes[2].set_ylim(0, max_speed * 1.3)

    for i, v in enumerate(df['Speed (s/img)']):
        axes[2].text(i, v + v * 0.05, f'{v:.3f}s', ha='center', fontweight='bold', fontsize=10)

    plt.tight_layout()
    plt.show()
else:
    print("No results to visualize!")

# Visualize predictions from 3 models on 2 sample images
print("\n" + "="*100)
print("SAMPLE PREDICTIONS VISUALIZATION (2 Sample Images)")
print("="*100)

# Select 2 random sample images
sample_indices = random.sample(range(len(test_data)), min(2, len(test_data)))

for sample_idx in sample_indices:
    sample_img_path = test_data[sample_idx]['image_path']

    print(f"\n{'─'*100}")
    print(f"SAMPLE IMAGE {sample_idx + 1}: {sample_img_path}")
    print(f"{'─'*100}")

    # Get ground truth labels for this image
    gt_labels = [item['label'] for item in test_data if item['image_path'] == sample_img_path]
    print(f"Ground Truth Labels: {gt_labels}")
    print(f"Total regions in this image: {len(gt_labels)}\n")

    # Get predictions with confidence threshold 0.3
    preds_crnn = inference_yolo_crnn(sample_img_path, conf_threshold=0.3)
    preds_trocr = inference_yolo_trocr(sample_img_path, conf_threshold=0.3)
    preds_easyocr = inference_easyocr(sample_img_path, conf_threshold=0.3)

    # Visualize
    fig, axes = plt.subplots(1, 3, figsize=(20, 8))

    for idx, (preds, title) in enumerate([
        (preds_crnn, 'YOLO + CRNN (Ours)'),
        (preds_trocr, 'YOLO + TrOCR'),
        (preds_easyocr, 'EasyOCR (End-to-End)')
    ]):
        img = cv2.imread(sample_img_path)
        img = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)

        for pred in preds:
            x, y, w, h = pred['bbox']
            cv2.rectangle(img, (x, y), (x+w, y+h), (0, 255, 0), 2)

            # Add text
            text = pred['text']
            conf = pred['confidence']
            label = f"{text} ({conf:.2f})"

            # Background for text
            (text_w, text_h), _ = cv2.getTextSize(label, cv2.FONT_HERSHEY_SIMPLEX, 0.5, 2)
            cv2.rectangle(img, (x, y-text_h-5), (x+text_w, y), (0, 255, 0), -1)
            cv2.putText(img, label, (x, y-5), cv2.FONT_HERSHEY_SIMPLEX, 0.5, (0, 0, 0), 2)

        axes[idx].imshow(img)
        axes[idx].set_title(title, fontsize=14, fontweight='bold')
        axes[idx].axis('off')

    plt.tight_layout()
    plt.show()

    # Print detection results
    print(f"  YOLO+CRNN detected: {len(preds_crnn)} regions")
    for i, pred in enumerate(preds_crnn):
        print(f"    {i+1}. {pred['text']} (conf: {pred['confidence']:.3f})")

    print(f"\n  YOLO+TrOCR detected: {len(preds_trocr)} regions")
    for i, pred in enumerate(preds_trocr):
        print(f"    {i+1}. {pred['text']} (conf: {pred['confidence']:.3f})")

    print(f"\n  EasyOCR detected: {len(preds_easyocr)} regions")
    for i, pred in enumerate(preds_easyocr):
        print(f"    {i+1}. {pred['text']} (conf: {pred['confidence']:.3f})")

    print("\n")